apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: emailservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/emailservice
    newTag: v0.10.6

configMapGenerator:
  - name: emailservice
    literals:
      - PORT=8080
      - DISABLE_PROFILER=1

generatorOptions:
  disableNameSuffixHash: true


resources:
- emailservice-dpl.yaml
- emailservice-svc.yaml
- emailservice-ingress-netpol.yaml
