apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-online-boutique
  
patches:
  - path: patches/patch-adservice.yaml
  - path: patches/patch-cartservice.yaml
  - path: patches/patch-checkoutservice.yaml
  - path: patches/patch-currencyservice.yaml
  - path: patches/patch-emailservice.yaml
  - path: patches/patch-frontend.yaml
  - path: patches/patch-paymentservice.yaml
  - path: patches/patch-productcatalogservice.yaml
  - path: patches/patch-recommendationservice.yaml
  - path: patches/patch-redis-cart.yaml
  - path: patches/patch-shippingservice.yaml

components:
  - ../../components/loadgenerator/

resources:
  - ../../base
  - namespace.yaml
  - frontend-ingress.yaml
  