apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-online-boutique

images:
  - name: adservice
    newName: 192.168.122.1:8082/microservices-demo/adservice
    newTag: v0.10.6

  - name: cartservice
    newName: 192.168.122.1:8082/microservices-demo/cartservice
    newTag: v0.10.6

  - name: checkoutservice
    newName: 192.168.122.1:8082/microservices-demo/checkoutservice
    newTag: v0.10.6

  - name: currencyservice
    newName: 192.168.122.1:8082/microservices-demo/currencyservice
    newTag: v0.10.6

  - name: emailservice
    newName: 192.168.122.1:8082/microservices-demo/emailservice
    newTag: v0.10.6

  - name: frontend
    newName: 192.168.122.1:8082/microservices-demo/frontend
    newTag: v0.10.6

  - name: paymentservice
    newName: 192.168.122.1:8082/microservices-demo/paymentservice
    newTag: v0.10.6

  - name: productcatalogservice
    newName: 192.168.122.1:8082/microservices-demo/productcatalogservice
    newTag: v0.10.6

  - name: recommendationservice
    newName: 192.168.122.1:8082/microservices-demo/recommendationservice
    newTag: v0.10.6

  - name: shippingservice
    newName: 192.168.122.1:8082/microservices-demo/shippingservice
    newTag: v0.10.6

  - name: redis
    newName: redis
    newTag: 8.10.1-alpine3.23

patches:
  - path: patches/patch-adservice.yaml
  - path: patches/patch-cartservice.yaml
  - path: patches/patch-checkoutservice.yaml
  - path: patches/patch-currencyservice.yaml
  - path: patches/patch-emailservice.yaml
  - path: patches/patch-frontend.yaml
  - path: patches/patch-paymentservice.yaml
  - path: patches/patch-productcatalogservice.yaml
  - path: patches/patch-recommendationservice.yaml
  - path: patches/patch-redis-cart.yaml
  - path: patches/patch-shippingservice.yaml

components:
  - ../../components/loadgenerator/

resources:
  - ../../base
  - namespace.yaml
  - frontend-ingress.yaml
  