apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-online-boutique
  namespace: argocd

spec:
  project: online-boutique

  source:
    repoURL: https://github.com/Alireza-Hoseini-sha/online-boutique-gitops.git 
    targetRevision: main
    path: overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-online-boutique

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
