apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: cartservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice
    newTag: v0.10.6

configMapGenerator:
  - name: cartservice
    literals:
      - REDIS_ADDR=redis-cart:6379

generatorOptions:
  disableNameSuffixHash: true

resources:
- cartservice-dpl.yaml
- cartservice-svc.yaml
- cartservice-ingress-netpol.yaml