apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- redis-cart-sts.yaml
- redis-cart-ingress-netpol.yaml
- redis-cart-svc.yaml
- redis-cart-pv.yaml 
- redis-cart-pvc.yaml