apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: redis
    newTag: 8.10.1-alpine3.23

generatorOptions:
  disableNameSuffixHash: true

resources:
- redis-cart-dpl.yaml
- redis-cart-ingress-netpol.yaml
- redis-cart-svc.yaml
