apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: productcatalogservice
    literals:
    - PORT=3550
    - DISABLE_PROFILER=1

generatorOptions:
  disableNameSuffixHash: true

resources:
- productcatalogservice-dpl.yaml
- productcatalogservice-svc.yaml
- productcatalogservice-ingress-netpol.yaml

