apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: adservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice
    newTag: v0.10.6
  
  - name: cartservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice
    newTag: v0.10.6
  
  - name: checkoutservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/checkoutservice
    newTag: v0.10.6
  
  - name: currencyservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/currencyservice
    newTag: v0.10.6

  - name: emailservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/emailservice
    newTag: v0.10.6
  
  - name: frontend
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/frontend
    newTag: v0.10.6

  - name: paymentservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/paymentservice
    newTag: v0.10.6

  - name: productcatalogservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/productcatalogservice
    newTag: v0.10.6

  - name: recommendationservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/recommendationservice
    newTag: v0.10.6

  - name: redis
    newName: redis
    newTag: 8.10.1-alpine3.23

  - name: shippingservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/shippingservice
    newTag: v0.10.6

resources:
  - adservice/
  - cartservice/
  - checkoutservice/
  - common/
  - currencyservice/
  - emailservice/
  - frontend/
  - paymentservice/
  - recommendationservice/
  - productcatalogservice/
  - redis-cart/
  - shippingservice/
  - gitlab-ci-svc-rbac.yaml