apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - namespace.yaml
  - adservice/
  - cartservice/
  - checkoutservice/
  - common/
  - currencyservice/
  - emailservice/
  - frontend/
  - paymentservice/
  - recommendationservice/
  - productcatalogservice/
  - redis-cart/
  - shippingservice/