apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: adservice
    newName: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice
    newTag: v0.10.6

configMapGenerator:
  - name: adservice
    literals:
      - PORT=9555

generatorOptions:
  disableNameSuffixHash: true
  

resources:
- adservice-dpl.yaml
- adservice-svc.yaml
- adservice-ingress-netpol.yaml
