apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: currencyservice
    literals:
      - PORT=7000
      - DISABLE_PROFILER=1

generatorOptions:
  disableNameSuffixHash: true


resources:
- currencyservice-dpl.yaml
- currencyservice-svc.yaml
- currencyservice-ingress-netpol.yaml
