apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: paymentservice
    literals:
    - PORT=50051
    - DISABLE_PROFILER=1

generatorOptions:
  disableNameSuffixHash: true

resources:
- paymentservice-dpl.yaml
- paymentservice-svc.yaml
- paymentservice-sa.yaml
- paymentservice-ingress-netpol.yaml
- paymentservice-roleBinding.yaml
- paymentservice-role.yaml
- paymentservice-secret.yaml
